# Generated by Django 5.2.14 on 2026-05-24 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready_for_review', 'Ready for Review'), ('failed', 'Failed')], default='processing', max_length=32)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('flagged_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_batches', to='core.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('parse_status', models.CharField(choices=[('parsed', 'Parsed'), ('error', 'Error')], default='parsed', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('batch', 'row_number')},
            },
        ),
    ]
