# Generated by Django 5.2.14 on 2026-05-24 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('sap_me2n', 'SAP ME2N'), ('sap_mb51', 'SAP MB51'), ('utility_portal', 'Utility Portal'), ('concur', 'Concur Itinerary'), ('navan', 'Navan Bookings')], max_length=32)),
                ('source_row_id', models.CharField(db_index=True, max_length=255)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=16)),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('purchased_goods', 'Purchased Goods (Spend)'), ('business_travel', 'Business Travel')], max_length=32)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending', max_length=16)),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('quantity_raw', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit_raw', models.CharField(blank=True, default='', max_length=32)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit_normalized', models.CharField(blank=True, default='', max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-activity_date', '-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
